<?xml version="1.0"?>
<package format="3">
  <name>hikrobot_camera</name>
  <version>0.1.0</version>
  <description>ROS 2 Humble camera driver for Hikrobot industrial cameras (MVS SDK).</description>
  <maintainer email="1423708426@qq.com">周银夕</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
